# Branch Protection Rules for AgentVibes
# This file documents the recommended branch protection settings
# Apply these settings in: Settings > Branches > Add rule

# For 'master' branch:
protection_rules:
  - name: master
    # Require PR reviews before merging
    required_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
      
    # Require status checks to pass
    required_status_checks:
      strict: true # Require branches to be up to date
      contexts:
        - "Test on ubuntu-latest / Node 20.x"
        - "Test on ubuntu-latest / Node 18.x"
        - "Code Coverage"
        - "Build Check"
        - "All CI Checks Passed"
        
    # Enforce all configured restrictions
    enforce_admins: false
    
    # Prevent force pushes and deletions
    allow_force_pushes: false
    allow_deletions: false
    
    # Require conversation resolution
    required_conversation_resolution: true
    
    # Require signed commits (optional)
    required_signatures: false